### ISSUE TITLE
FBReader DIV elements ignoring top-margin & bottom-margin CSS on Kindle Fire

### ISSUE THREAD

**Issue by dmich2** [geometer/FBReaderJ#463]
Second Generation Kindle Fire (2012), System Version: 10.5.1
FBReader 2.8.2 (2080231)

Using latest apk at https://fbreader.org/files/android/FBReaderJ_ice-cream-sandwich.apk

```css

.extractletter {
    display: block;
    margin-bottom: 1em;
    margin-top: 1em
    }
```
```html
<p>para above</p>
<div class="extractletter">
<p class="extractlettersalutation"><span class="italic">Hi,</span></p>
<p class="extractlettertext"><span class="italic">This example letter should
have blank space above and below it when viewed on a Kindle Fire but it
does not.</span></p>
<p class="extractlettersignature"><span class="italic">Issue Reporter</span></p>
</div>
<p>para below</p>
```
As described in the letter extract, this displays without 1em whitespace above and below the sample letter.
