### ISSUE TITLE
`<hr>` with CSS visibility:hidden + padding should show up as paragraph break but in FBReader it doesn't

### ISSUE THREAD

**Issue by ghost** [geometer/FBReaderJ#473]
I tried to introduce a paragraph break (empty blank line between two paragraphs with the following approach):

```html
<p>Some text</p>
<hr class="paragraph_break"/>
<p>Following text</p>
```
```css
.paragraph_break {visibility: hidden; height:0px;border-style:none;display:block;padding-bottom:0.5em;padding-top:0.5em;}
```
This works in all readers I have tested (Calibre, Kindle Previewer 3, Microsoft Edge built-in EPUB reader) just fine... but not in FBReader for Android. There, the `<hr>` just disappears without any indication anything is there, not even a hint of additional vertical blank space.

This seems like a major bug to me, because semantically, clearly there should be a visible separator there, and `visibility:hidden` is pretty well-defined (and it's *not* the same as `display:none`).
